### ISSUE TITLE
Cannot use pyudev with OSX

### ISSUE THREAD

**Issue by ronanamsterdam** [pyudev/pyudev#185]
Hey there.

Firstly tried to use pyudev from
```pip install pyudev```
Got error on ```import pyudev```

Then tried cloned the src from here and installed with local virtualenv -> same result:

```
Python 2.7.9 (default, Jun 15 2016, 21:00:12)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyudev
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.11-x86_64/egg/pyudev/__init__.py", line 63, in <module>
  File "build/bdist.macosx-10.11-x86_64/egg/pyudev/monitor.py", line 42, in <module>
  File "build/bdist.macosx-10.11-x86_64/egg/pyudev/_os/__init__.py", line 28, in <module>
  File "build/bdist.macosx-10.11-x86_64/egg/pyudev/_os/poll.py", line 38, in <module>
  File "build/bdist.macosx-10.11-x86_64/egg/pyudev/_os/poll.py", line 46, in Poll
AttributeError: 'module' object has no attribute 'POLLIN'
```

**Comment by mulkieran** [comment]
Hi! pyudev isn't expected to work on Mac OS X. It lists only Linux in its setup file. Patches that allow it to work on Mac OS X are welcome, so long as they are not too invasive.

**Comment by ronanamsterdam** [comment]
Got it :) will try to investigate and help
