### ISSUE TITLE
Monitor Failure On Embedded System

### ISSUE THREAD

**Issue by SoundsSerious** [pyudev/pyudev#402]
Hi, new to pyudev.

Been seeing a weird error running on a raspberry pi ubuntu core 18 with udevadm version 229. Think this might have been referenced in #362 

I am experiencing an issue where certain events will crash both the async daemon and the synchronous system.

Here is a normal remove event from a simple optical mouse in the udevadm tool
```
KERNEL[19210.795733] remove   /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:047D:102A.0008/input/input13/mouse0 (input)
UDEV  [19210.800559] remove   /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:047D:102A.0008/input/input13/mouse0 (input)
KERNEL[19210.808260] remove   /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:047D:102A.0008/input/input13/event1 (input)
UDEV  [19210.810404] remove   /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:047D:102A.0008/input/input13/event1 (input)
KERNEL[19210.824450] remove   /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:047D:102A.0008/input/input13 (input)
KERNEL[19210.824640] remove   /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:047D:102A.0008/hidraw/hidraw0 (hidraw)
KERNEL[19210.825434] remove   /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:047D:102A.0008 (hid)
KERNEL[19210.825957] remove   /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0 (usb)
UDEV  [19210.828787] remove   /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:047D:102A.0008/input/input13 (input)
UDEV  [19210.830096] remove   /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:047D:102A.0008/hidraw/hidraw0 (hidraw)
KERNEL[19210.830431] remove   /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3 (usb)
UDEV  [19210.835680] remove   /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:047D:102A.0008 (hid)
UDEV  [19210.838388] remove   /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0 (usb)
UDEV  [19210.840369] remove   /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3 (usb) 
```

Here is the mix of events that work and fail using a restarting synchronous montor.poll:

```
background event remove: /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:047D:102A.0007/input/input8/mouse0
background event remove: /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:047D:102A.0007/input/input8/event1
background event remove: /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:047D:102A.0007/input/input8
background event remove: /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:047D:102A.0007/hidraw/hidraw0
Traceback (most recent call last):
  File "adapt-linux-embeded/usb_recognition.py", line 58, in start_polling_udev_events
    for device in iter(monitor.poll, None):
  File "/home/turnaroundfactor/.local/lib/python3.5/site-packages/pyudev/monitor.py", line 355, in poll
    return self._receive_device()
  File "/home/turnaroundfactor/.local/lib/python3.5/site-packages/pyudev/monitor.py", line 294, in _receive_device
    device_p = self._libudev.udev_monitor_receive_device(self)
  File "/home/turnaroundfactor/.local/lib/python3.5/site-packages/pyudev/_ctypeslib/_errorcheckers.py", line 103, in check_errno_on_null_pointer_return
    raise exception_from_errno(errnum)
ValueError: Invalid argument
background event remove: /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:047D:102A.0007
Traceback (most recent call last):
  File "adapt-linux-embeded/usb_recognition.py", line 58, in start_polling_udev_events
    for device in iter(monitor.poll, None):
  File "/home/turnaroundfactor/.local/lib/python3.5/site-packages/pyudev/monitor.py", line 355, in poll
    return self._receive_device()
  File "/home/turnaroundfactor/.local/lib/python3.5/site-packages/pyudev/monitor.py", line 294, in _receive_device
    device_p = self._libudev.udev_monitor_receive_device(self)
  File "/home/turnaroundfactor/.local/lib/python3.5/site-packages/pyudev/_ctypeslib/_errorcheckers.py", line 103, in check_errno_on_null_pointer_return
    raise exception_from_errno(errnum)
ValueError: Invalid argument
background event remove: /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3/1-1.3:1.0
Traceback (most recent call last):
  File "adapt-linux-embeded/usb_recognition.py", line 58, in start_polling_udev_events
    for device in iter(monitor.poll, None):
  File "/home/turnaroundfactor/.local/lib/python3.5/site-packages/pyudev/monitor.py", line 355, in poll
    return self._receive_device()
  File "/home/turnaroundfactor/.local/lib/python3.5/site-packages/pyudev/monitor.py", line 294, in _receive_device
    device_p = self._libudev.udev_monitor_receive_device(self)
  File "/home/turnaroundfactor/.local/lib/python3.5/site-packages/pyudev/_ctypeslib/_errorcheckers.py", line 103, in check_errno_on_null_pointer_return
    raise exception_from_errno(errnum)
ValueError: Invalid argument
background event remove: /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.3
```

Very frustrating as none of the events look that different! Whats going on!?

**Comment by SoundsSerious** [comment]
Having dug through the code it looks like the failure is due to a null device being found. Why allow the monitor to crash during this scenario?

```
def check_errno_on_null_pointer_return(result, _func, *_args):
    """Error checker to check the system ``errno`` as returned by
    :func:`ctypes.get_errno()`.
    If ``result`` is a null pointer, an exception according to this errno is
    raised.  Otherwise nothing happens.
    """
    # pylint: disable=invalid-name
    if not result:
        errnum = get_errno()
        if errnum != 0:
            raise exception_from_errno(errnum) < Fails Here
    return result
```

Perhaps related to #362 the raspberry core version of linux has some weird c structure that doesn't match the pointers?

**Comment by SoundsSerious** [comment]
For now i'm using a modified version of the code with no error handler on monitor_recieve and that seems to be "solving the problem"

**Comment by SoundsSerious** [comment]
it appears that i get all events matching the UDEV vs KERNEL events. I see from the documentation that the default is to only display UDEV... however perhaps in the case of this issue (raspberry pi linux) and #362 (docker container) perhaps the kernel filter is different? That would explain the unmapped c-type and subsequent failure.

**Comment by SoundsSerious** [comment]
This issue disappeared on Ubuntu20.04 vs 16.04.

I think the solution to it would be to create as a special error handler for this call only that warns instead of raises

**Comment by mulkieran** [comment]
@SoundsSerious: Can you create a PR?

**Comment by SoundsSerious** [comment]
@mulkieran

Yea, can do. Moving this week but we are planning on using this in our project so i want it to be failsafe :)

Great work on the library!

**Comment by SoundsSerious** [comment]
@mulkieran 

Sorry can't figure out how to create a pull request for #402

I intended to add a function to _errorcheckers.py:

```
def check_errno_on_null_pointer_return_tolerate_failure(result, _func, *_args):
    """Error checker to check the system ``errno`` as returned by
    :func:`ctypes.get_errno()`.
    If ``result`` is a null pointer, an exception according to this errno is
    raised.  Otherwise nothing happens.
    """
    # pylint: disable=invalid-name
    if not result:
        errnum = get_errno()
        if errnum != 0:
            print('Warning Null Pointer Return{}'.format(exception_from_errno(errnum)))
            return None
    return result
```

And modify line 258 in libudev.py to:

```
udev_monitor_receive_device=check_errno_on_null_pointer_return_tolerate_failure,
```

**Comment by mulkieran** [comment]
The problem is the branch you've checked out from and the default branch for the repo. Try checking out again, switching to master branch, adding your changes, and then making a PR against master. I think that will work.

**Comment by SoundsSerious** [comment]
Thanks for the instructions.

Definetly not a git wizard, getting this error from the cmd line:

```
git request-pull HEAD~1 https://github.com/pyudev/pyudev master
warn: No match for commit f2c00d75b53d2dc6ed6f5e3a71d264245871eafe found at https://github.com/pyudev/pyudev
warn: Are you sure you pushed 'master' there?
The following changes since commit 62c4dd1e3d4bd28ad26bbfa0a14933d7a3d3be66:

  Merge pull request #400 from Skrupellos/glib-tests (2020-07-06 20:10:27 -0400)

are available in the Git repository at:

  https://github.com/pyudev/pyudev master

for you to fetch changes up to f2c00d75b53d2dc6ed6f5e3a71d264245871eafe:

  Resolve Issue Monitor Failure On Embedded System #402 (2020-08-12 11:30:12 -0400)

----------------------------------------------------------------
SoundsSerious (1):
      Resolve Issue Monitor Failure On Embedded System #402

 src/pyudev/_ctypeslib/_errorcheckers.py | 15 +++++++++++++++
 src/pyudev/_ctypeslib/libudev.py        |  2 +-
 2 files changed, 16 insertions(+), 1 deletion(-)
```

**Comment by SoundsSerious** [comment]
When i try through vs code it gives me a permission error.
