### ISSUE TITLE
Test suite fails against systemd 250

### ISSUE THREAD

**Issue by DimStar77** [pyudev/pyudev#457]
systemd 250 has been released. When updating to systemd/udev 250, pyudev's own test suite fails with:

```
[   71s] =========================== short test summary info ============================
[   71s] FAILED tests/test_device.py::TestAttributes::test_asbool - KeyError: 'eject'
[   71s] ===== 1 failed, 123 passed, 36 skipped, 7 deselected, 4 warnings in 43.78s =====
```

```
[   71s] =================================== FAILURES ===================================
[   71s] __________________________ TestAttributes.test_asbool __________________________
[   71s] 
[   71s] self = <tests._device_tests._attributes_tests.TestAttributes object at 0x7f28c50789d0>
[   71s] 
[   71s] >   ???
[   71s] 
[   71s] tests/_device_tests/_attributes_tests.py:112: 
[   71s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   71s] tests/_device_tests/_attributes_tests.py:123: in test_asbool
[   71s]     device.attributes.asbool(key)
[   71s] ../../BUILDROOT/python-pyudev-0.22.0+git.1642212208.d5630bf-3.3.x86_64/usr/lib/python3.9/site-packages/pyudev/device/_device.py:1260: in asbool
[   71s]     return string_to_bool(self.asstring(attribute))
[   71s] ../../BUILDROOT/python-pyudev-0.22.0+git.1642212208.d5630bf-3.3.x86_64/usr/lib/python3.9/site-packages/pyudev/device/_device.py:1228: in asstring
[   71s]     return ensure_unicode_string(self._get(attribute))
[   71s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   71s] 
[   71s] self = <pyudev.device._device.Attributes object at 0x7f28c4f2c1c0>
[   71s] attribute = 'eject'
[   71s] 
[   71s]     def _get(self, attribute):
[   71s]         """
[   71s]         Get the given system ``attribute`` for the device.
[   71s]     
[   71s]         :param attribute: the key for an attribute value
[   71s]         :type attribute: unicode or byte string
[   71s]         :returns: the value corresponding to ``attribute``
[   71s]         :rtype: an arbitrary sequence of bytes
[   71s]         :raises KeyError: if no value found
[   71s]         """
[   71s]         value = self._libudev.udev_device_get_sysattr_value(
[   71s]             self.device, ensure_byte_string(attribute)
[   71s]         )
[   71s]         if value is None:
[   71s] >           raise KeyError(attribute)
[   71s] E           KeyError: 'eject'
[   71s] 
[   71s] ../../BUILDROOT/python-pyudev-0.22.0+git.1642212208.d5630bf-3.3.x86_64/usr/lib/python3.9/site-packages/pyudev/device/_device.py:1198: KeyError
[   71s] ---------------------------------- Hypothesis ----------------------------------
[   71s] Falsifying example: test_asbool(
[   71s]     a_context=<pyudev.core.Context at 0x7f28c5527cd0>,
[   71s]     device_datum=DeviceData(/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:1e),
[   71s]     self=<tests._device_tests._attributes_tests.TestAttributes at 0x7f28c50789d0>,
[   71s] )
[   71s] =============================== warnings summary ===============================
[   71s] tests/test_device.py::TestDevice::test_find_parent_no_devtype_mock
[   71s] tests/test_device.py::TestDevice::test_find_parent_with_devtype_mock
[   71s]   /usr/lib/python3.9/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function Device.__del__ at 0x7f28c60af160>
[   71s]   
[   71s]   Traceback (most recent call last):
[   71s]     File "/home/abuild/rpmbuild/BUILDROOT/python-pyudev-0.22.0+git.1642212208.d5630bf-3.3.x86_64/usr/lib/python3.9/site-packages/pyudev/device/_device.py", line 491, in __del__
[   71s]       self._libudev.udev_device_unref(self)
[   71s]   ctypes.ArgumentError: argument 1: <class 'TypeError'>: expected LP_udev_device instance instead of _SentinelObject
[   71s]   
[   71s]     warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
[   71s] 
[   71s] tests/test_monitor.py::TestMonitor::test_from_netlink_source_udev_mock
[   71s] tests/test_monitor.py::TestMonitor::test_from_netlink_source_kernel_mock
[   71s]   /usr/lib/python3.9/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function Monitor.__del__ at 0x7f28c60b9a60>
[   71s]   
[   71s]   Traceback (most recent call last):
[   71s]     File "/home/abuild/rpmbuild/BUILDROOT/python-pyudev-0.22.0+git.1642212208.d5630bf-3.3.x86_64/usr/lib/python3.9/site-packages/pyudev/monitor.py", line 88, in __del__
[   71s]       self._libudev.udev_monitor_unref(self)
[   71s]   ctypes.ArgumentError: argument 1: <class 'TypeError'>: expected LP_udev_monitor instance instead of _SentinelObject
[   71s]   
[   71s]     warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
[   71s] 
[   71s] -- Docs: https://docs.pytest.org/en/stable/warnings.html

```

**Comment by DimStar77** [comment]
(tested with update up to 3f60ee80d424178008b39c5ca323cc1a15f2b64e)

**Comment by mulkieran** [comment]
Thanks for the report. These tests are not reliable, because they make use of the actual udev environment which can fluctuate during the test itself. That looks like what's happening here. I think the test itself could be hardened, to catch the KeyError, if it is raised, and ignore it; I'll see if that looks like it would work If you are running the tests as part of a packaging check, I'ld definitely advise against doing that.
