### ISSUE TITLE
UnicodeDecodeError when reading GPT PartitionName

### ISSUE THREAD

**Issue by ogayot** [pyudev/pyudev#490]
Hello,
In Subiquity (the Ubuntu Server installer), we are using pyudev to list and retrieve information about the different devices that we can install on. We are iterating over all the properties of the block devices and exporting the data as JSON.

Some users set a name to their GPT partitions (by setting the PartitionName field) and sometimes include accentuated characters in the name (or other special characters). My understanding of the PartitionName field is that it is UTF-16 encoded.

When iterating over the properties of the block devices in pyudev (and specifically the PARTNAME property), accents or special characters cause pyudev to raise a UnicodeDecodeError exception:

```python
import pyudev

context = pyudev.Context()

for device in context.list_devices(subsystem='block'):
    if 'PARTNAME' in device:
        print(device['PARTNAME'])
```

```
Traceback (most recent call last):
  File "/home/olivier/file.py", line 6, in <module>
    if 'PARTNAME' in device:
       ^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 780, in __contains__
  File "/usr/lib/python3/dist-packages/pyudev/device/_device.py", line 973, in __getitem__
    return self.properties.__getitem__(prop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pyudev/device/_device.py", line 1101, in __getitem__
    return ensure_unicode_string(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pyudev/_util.py", line 56, in ensure_unicode_string
    value = value.decode(sys.getfilesystemencoding())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 7: invalid start byte
```
For some reason, the PARTNAME property looks broken (i.e., it is not valid UTF-8 nor UTF-16). It is as if the MSB from all the UTF-16 characters got dropped:

 * letter A in UTF-16 is 0x0041. It becomes 0x41 (which is letter A)
 * e-ecute (é) in UTF-16 is 0x00E9. It becomes 0xE9
 * euro sign (€) in UTF-16 is 0x20AC. It becomes 0xAC
 * pound sign (£) in UTF-16 is 0x00A3. It becomes 0xA3

Below are the relevant properties as shown by `udevadm info --export-db | less`:
```
E: PARTNAME=Donn<E9>es
E: ID_PART_ENTRY_NAME=Données
E: DEVLINKS=/dev/disk/by-partlabel/Données /dev/disk/by-partuuid/4f685f6a-606d-b845-8596-562dab728429
```
The other properties (e.g., ID_PART_ENTRY_NAME and DEVLINKS) look okay, but PARTNAME does not.

At this point, I'm not sure if this is purely a problem in pyudev. Maybe in udev or in lower levels? That said, I wonder if there is something we can do at pyudev level to, at least, work around the issue.

Is there a known way to avoid this issue when iterating over the properties of devices? If not, I was thinking of adding a way to configure what `errors` parameter would be passed to [bytes.decode](https://docs.python.org/3/library/stdtypes.html#bytes.decode) in `ensure_unicode_string` when accessing a property of a Device. Maybe at the device level or at the context level. Does it sound like a viable solution? 

### Steps to reproduce
```sh
# Create a 100MiB file under /tmp
dd if=/dev/zero of=/tmp/test.img bs=1M count=100
# Create a GPT partition table with one partition named "Données" (Data in French).
# This sets the GPT PartitionName field.
sfdisk /tmp/test.img <<EOF
label: gpt
label-id: CAEC69BF-F7D7-5F4E-9657-2A400D14F09A
device: test.img
unit: sectors
first-lba: 2048
last-lba: 204766
sector-size: 512

test.img1 : start=        2048, size=      200704, type=0FC63DAF-8483-4772-8E79-3D69D8477DE4, uuid=4F685F6A-606D-B845-8596-562DAB728429, name="Donn\xc3\xa9es"
EOF
# Make this partition table visible system-wide by binding it to a /dev/loop device.
sudo losetup -fP /tmp/test.img
```

Next, run the following code:
```python
import pyudev

context = pyudev.Context()

for device in context.list_devices(subsystem='block'):
    if 'PARTNAME' in device:
        print(device['PARTNAME'])
```
output when I run it:
```
Traceback (most recent call last):
  File "/home/olivier/file.py", line 6, in <module>
    if 'PARTNAME' in device:
       ^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 780, in __contains__
  File "/usr/lib/python3/dist-packages/pyudev/device/_device.py", line 973, in __getitem__
    return self.properties.__getitem__(prop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pyudev/device/_device.py", line 1101, in __getitem__
    return ensure_unicode_string(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pyudev/_util.py", line 56, in ensure_unicode_string
    value = value.decode(sys.getfilesystemencoding())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 7: invalid start byte
```

Thank you!
Olivier

**Comment by ogayot** [comment]
Hi again,

@dbungert and I did some research and we think the PARTNAME being wrong UTF-8 actually comes straight from the kernel:

https://elixir.bootlin.com/linux/v6.3/source/block/partitions/efi.c#L750
https://elixir.bootlin.com/linux/v6.3/source/block/partitions/efi.c#L678

After reading the code, it seems that the kernel attempts but fails to produce a valid 7-bit ASCII string out of the UTF-16 partition name containing accents.
Unlike in the glibc, the isprint function in the kernel returns 1 for some characters in the [0x7f; 0xff] range.

https://elixir.bootlin.com/linux/v6.3/source/lib/ctype.c#L12

Thank you!
Olivier

**Comment by RoyalPanda** [comment]
Hi,
I have the same issue but with HID device name : 
```
File "/usr/lib/python3.11/site-packages/ds4drv/backends/hidraw.py", line 153, in devices
    cls = HID_DEVICES.get(hid_device.get("HID_NAME"))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 774, in get
  File "/home/gerard/.local/lib/python3.11/site-packages/pyudev/device/_device.py", line 973, in __getitem__
    return self.properties.__getitem__(prop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gerard/.local/lib/python3.11/site-packages/pyudev/device/_device.py", line 1101, in __getitem__
    return ensure_unicode_string(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gerard/.local/lib/python3.11/site-packages/pyudev/_util.py", line 56, in ensure_unicode_string
    value = value.decode(sys.getfilesystemencoding())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 10: invalid start byte
```
and udevadm info --export-db show me this device : 

```
...
P: /devices/pci0000:00/0000:00:1d.0/usb1/1-1/1-1.6/1-1.6:1.2/0003:046D:C52B.0003
/0003:046D:408A.0004/input/input23
M: input23
R: 23
U: input
E: DEVPATH=/devices/pci0000:00/0000:00:1d.0/usb1/1-1/1-1.6/1-1.6:1.2/0003:046D:C
52B.0003/0003:046D:408A.0004/input/input23
E: SUBSYSTEM=input
E: PRODUCT=3/46d/408a/111
E: NAME="Logitech G<A9>F^^@"
...
```
I think it was introduced lately as I don't plugged new hardware and never had this issue.

Regards,
Clément

**Comment by RoyalPanda** [comment]
I could trigger it by easy code :
```
import pyudev

context = pyudev.Context()

for device in context.list_devices():
    if 'HID_NAME' in device.properties:
        print(device.properties['HID_NAME'])
```

**Comment by ogayot** [comment]
Hello,

I submitted a patch to fix the issue in the kernel for GPT partition names. I'd assume a similar patch would be needed for HID devices.

https://lore.kernel.org/linux-efi/f19a6d8a-c85a-963e-412e-efaa7f520453@canonical.com/T/#t

Even if the patch/patches get(s) accepted and merged upstream, it will be a long time until pyudev users stop using affected kernel versions. Therefore, I still hope there is something we can do in pyudev itself.

Thanks,
Olivier

**Comment by CheckYourFax** [comment]
> Hello,
> 
> I submitted a patch to fix the issue in the kernel for GPT partition names. I'd assume a similar patch would be needed for HID devices.
> 
> https://lore.kernel.org/linux-efi/f19a6d8a-c85a-963e-412e-efaa7f520453@canonical.com/T/#t
> 
> Even if the patch/patches get(s) accepted and merged upstream, it will be a long time until pyudev users stop using affected kernel versions. Therefore, I still hope there is something we can do in pyudev itself.
> 
> Thanks, Olivier

Is there a reason why this was never merged?

**Comment by ogayot** [comment]
> Is there a reason why this was never merged?

Not sure. I've never received any acknowledgment or feedback on the patch by the kernel subsystem maintainers. I don't think it has ever been looked at.

Actually, I  resent the same patch again last week, but it hasn't gotten any more visibility so far.

https://lore.kernel.org/linux-block/54095d2f-daea-4e4a-9542-f6a2b7603672@canonical.com/T/#t

**Comment by jstasiak** [comment]
Posting just because I saw no comments about this: the v3 of the patch was merged a week ago it seems, congrats: https://lore.kernel.org/linux-block/174118592720.8596.17751872254586866019.b4-ty@kernel.dk/T/#t

**Comment by CheckYourFax** [comment]
https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.13.7

It's pushed to stable.
