### ISSUE TITLE
3.16.0: pyupgrate fails with call trace on sympy

### ISSUE THREAD

**Issue by kloczek** [pyudev/pyudev#515]
`pyupgrade` fails on filtering code of `sympy` (https://github.com/sympy/sympy/).
```console
+ pyupgrade --py310-plus --exit-zero-even-if-changed sympy/polys/numberfields/resolvent_lookup.py
Traceback (most recent call last):
  File "/usr/bin/pyupgrade", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/pyupgrade/_main.py", line 385, in main
    ret |= _fix_file(filename, args)
  File "/usr/lib/python3.10/site-packages/pyupgrade/_main.py", line 318, in _fix_file
    contents_text = _fix_plugins(
  File "/usr/lib/python3.10/site-packages/pyupgrade/_main.py", line 62, in _fix_plugins
    callbacks = visit(FUNCS, ast_obj, settings)
  File "/usr/lib/python3.10/site-packages/pyupgrade/_data.py", line 86, in visit
    for offset, token_func in ast_func(state, node, parent):
  File "/usr/lib/python3.10/site-packages/pyupgrade/_plugins/legacy.py", line 211, in visit_Module
    visitor.visit(node)
  File "/usr/lib64/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/usr/lib64/python3.10/ast.py", line 426, in generic_visit
    self.visit(item)
  File "/usr/lib64/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/usr/lib64/python3.10/ast.py", line 428, in generic_visit
    self.visit(value)
  File "/usr/lib64/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/usr/lib64/python3.10/ast.py", line 426, in generic_visit
    self.visit(item)
  File "/usr/lib64/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/usr/lib64/python3.10/ast.py", line 426, in generic_visit
    self.visit(item)
  File "/usr/lib64/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/usr/lib/python3.10/site-packages/pyupgrade/_plugins/legacy.py", line 111, in _visit_scope
    self.generic_visit(node)
  File "/usr/lib64/python3.10/ast.py", line 428, in generic_visit
    self.visit(value)
  File "/usr/lib64/python3.10/ast.py", line 418, in visit
    return visitor(node)

[..]

  File "/usr/lib64/python3.10/ast.py", line 428, in generic_visit
    self.visit(value)
  File "/usr/lib64/python3.10/ast.py", line 418, in visit
    return visitor(node)
  File "/usr/lib64/python3.10/ast.py", line 422, in generic_visit
    for field, value in iter_fields(node):
  File "/usr/lib64/python3.10/ast.py", line 262, in iter_fields
    yield field, getattr(node, field)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by mulkieran** [comment]
@kloczek What should this fact mean to pyudev?

**Comment by kloczek** [comment]
Sorry wrong repo.
Closing.
