### ISSUE TITLE
library locating/loading issue on systems without library cache

### ISSUE THREAD

**Issue by yegorich** [pyudev/pyudev#83]
I've tried pyudev on an ARM device (root file system build with Buildroot) and I had a problem with find_library routine. PyUSB project has similar issue and they workarounded it with the following commit: walac/pyusb#29
Could you implement similar workaround?
Thanks.

**Comment by mulkieran** [comment]
Please be as detailed and specific about the problem that you are encountering as is possible.

**Comment by yegorich** [comment]
See following output:

Python 2.7.10 (default, Aug 27 2015, 12:26:41)
[GCC 4.9.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyudev
>>> context = pyudev.Context()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pyudev-0.17dev_20150831-py2.7.egg/pyudev/core.py", line 95, in __init__
  File "/usr/lib/python2.7/site-packages/pyudev-0.17dev_20150831-py2.7.egg/pyudev/_libudev.py", line 217, in load_udev_library
ImportError: No library named udev

But I have the libraries there:
# ls -l /lib/libudev.so.1*
lrwxrwxrwx    1 root     root            16 Aug 27 10:29 /lib/libudev.so.1 -> libudev.so.1.6.3
-rwxr-xr-x    1 root     root        105552 Aug 31 05:58 /lib/libudev.so.1.6.3
# ls -l /usr/lib/libudev.so*
lrwxrwxrwx    1 root     root            26 Aug 27 10:29 /usr/lib/libudev.so -> ../../lib/libudev.so.1.6.3

This problem is known (https://bugs.python.org/issue13508), but so far there is no official fix. So PyUSB devs had to create a workaround.

**Comment by mulkieran** [comment]
Ok. Thanks for the info. The whole thing looks really ugly. I'm afraid the problem will be stuck low on my list of priorities. A PR would move it up a good deal, but it would need to have a good test case along with it.

**Comment by mulkieran** [comment]
What is the consequence of loading an incompatible library? Immediate failure, or something more subtle?

**Comment by yegorich** [comment]
Immediate failure is the consequence.

**Comment by mulkieran** [comment]
This is still a problem, and the solution is not obvious, see: https://bugs.python.org/issue13508.

**Comment by mulkieran** [comment]
I do not think this problem should be solved in pyudev. If it must be solved, and it won't be solved in Python libraries anytime soon, it should be solved by some other external entity.

**Comment by mulkieran** [comment]
Find out whether the cffi alternative will be any help.

**Comment by yegorich** [comment]
Haven't thought about it. CFFI is now well integrated into Buildroot, https://pypi.python.org/pypi/smbus-cffi/ and https://pypi.python.org/pypi/cryptography are already there and working.
